model_providers:
  - provider_name: truefoundry
    api_format: openai
    base_url: https://llm-gateway.truefoundry.com/api/inference/openai
    api_key_env_var: TFY_API_KEY
    llm_model_ids:
      - "openai-main/gpt-4o-mini"
      - "openai-main/gpt-4-turbo"
      - "azure-openai/gpt-4"
      - "together-ai/llama-3-70b-chat-hf"
    embedding_model_ids:
      - "openai-main/text-embedding-ada-002"
    reranking_model_ids: []
    default_headers:
      "X-TFY-METADATA": '{"tfy_log_request": "true", "Custom-Metadata": "Cognita-LLM-Request"}'

  - provider_name: local-infinity
    api_format: openai
    base_url: http://infinity.cognita.svc.cluster.local:8000
    api_key_env_var: INFINITY_API_KEY
    llm_model_ids: []
    embedding_model_ids:
      - "mixedbread-ai/mxbai-embed-large-v1"
    reranking_model_ids:
      - "mixedbread-ai/mxbai-rerank-xsmall-v1"
    default_headers: {}

  - provider_name: faster-whisper
    api_format: openai
    base_url: http://whisper.cognita.svc.cluster.local:8000
    api_key_env_var: ""
    llm_model_ids: []
    embedding_model_ids: []
    reranking_model_ids: []
    audio_model_ids:
      - "Systran/faster-distil-whisper-large-v3"
    default_headers: {}
